name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Build
      run: |
        npm install
        npm run build
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: dist/win-unpacked
